### ISSUE TITLE
Code review outcomes

### ISSUE THREAD

**Issue by andybondar** [luchare-hash/devops-6-task#1]
Hi,
Again, good job in general.

However, the deployment didn't work for me right away. That's because the absolute paths that you used in the Deployment configuration to refer to some GCP resources and their properties, like `network` and `machineType`. Use relative paths instead:

```diff
-     machineType: https://www.googleapis.com/compute/v1/projects/devops-task-6/zones/europe-west3-a/machineTypes/e2-micro
+     machineType: zones/europe-west3-a/machineTypes/e2-micro

-     - network: https://www.googleapis.com/compute/v1/projects/devops-task-6/global/networks/default
+     - network: global/networks/default
```
Also, it'd be nice to have a README file with a small description of what this deployment does and how it works.

**Comment by luchare-hash** [comment]
Hi,
thank you more much. I will use relative paths instead of absolute paths and I will add Readme.
